baseURL = 'https://johnrandall.com/'
languageCode = 'en-us'
title = 'John Randall'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  disableSpecial1stPost = true

  [params.profileMode]
    enabled = true
    title = "John Randall"
    subtitle = "Software engineer in Montclair, NJ."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/johntrandall"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/johntrandall/"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:john@johnrandall.com"
